---
# task for hadenlabs.java

- name: Install packages via pip java
  become: yes
  pip: name="{{ item.name }}" version="{{ item.version }}"
  when:
    - java_pip_dependencies is defined
  with_items: java_pip_dependencies
