---
# task for hadenlabs.java

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ _java_templates | default([]) }}"
  when:
    - _java_templates is defined
